channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - flask=3.1.0
  - click=8.1.8
  - itsdangerous=2.2.0
  - jinja2=3.1.6
  - markupsafe=3.0.2
  - packaging=25.0
  - greenlet=3.2.1
  - mysql-connector-python=9.3.0
  - pip
  - pip:
      - bidict==0.23.1
      - blinker==1.9.0
      - cysystemd==2.0.1
      - dnspython==2.7.0
      - eventlet==0.39.1
      - Flask-MQTT==1.2.1
      - Flask-SocketIO==5.5.1
      - gunicorn==23.0.0
      - paho-mqtt==1.6.1
      - PyMySQL==1.1.1
      - python-engineio==4.12.0
      - python-socketio==5.13.0
      - simple-websocket==1.1.0
